//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning_Management_System.Models.Generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absensi
    {
        public int IdAbsen { get; set; }
        public int IdJadwal { get; set; }
        public int IdSiswa { get; set; }
        public Nullable<System.DateTime> WaktuAbsen { get; set; }
        public string Status { get; set; }
        public string Catatan { get; set; }
    
        public virtual JadwalAbsen JadwalAbsen { get; set; }
        public virtual Users Users { get; set; }
    }
}
