//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning_Management_System.Models.Generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class JadwalAbsen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JadwalAbsen()
        {
            this.Absensi = new HashSet<Absensi>();
        }
    
        public int IdJadwal { get; set; }
        public int IdKelas { get; set; }
        public int PertemuanKe { get; set; }
        public System.DateTime Tanggal { get; set; }
        public System.TimeSpan JamMulai { get; set; }
        public System.TimeSpan JamSelesai { get; set; }
        public bool IsOpen { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Absensi> Absensi { get; set; }
        public virtual Kelas Kelas { get; set; }
    }
}
