//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning_Management_System.Models.Generator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_Learning_Management_SystemEntities : DbContext
    {
        public db_Learning_Management_SystemEntities()
            : base("name=db_Learning_Management_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absensi> Absensi { get; set; }
        public virtual DbSet<JadwalAbsen> JadwalAbsen { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Kelas> Kelas { get; set; }
        public virtual DbSet<Materi> Materi { get; set; }
        public virtual DbSet<MemberKelas> MemberKelas { get; set; }
        public virtual DbSet<NilaiQuiz> NilaiQuiz { get; set; }
        public virtual DbSet<Notifikasi> Notifikasi { get; set; }
        public virtual DbSet<OpsiJawaban> OpsiJawaban { get; set; }
        public virtual DbSet<PengumpulanTugas> PengumpulanTugas { get; set; }
        public virtual DbSet<Profiles> Profiles { get; set; }
        public virtual DbSet<ProgresMateri> ProgresMateri { get; set; }
        public virtual DbSet<Quiz> Quiz { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SoalQuiz> SoalQuiz { get; set; }
        public virtual DbSet<StreamPostingan> StreamPostingan { get; set; }
        public virtual DbSet<Tugas> Tugas { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
