//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning_Management_System.Models.Generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materi()
        {
            this.ProgresMateri = new HashSet<ProgresMateri>();
        }
    
        public int IdMateri { get; set; }
        public int IdKelas { get; set; }
        public int PertemuanKe { get; set; }
        public string JudulMateri { get; set; }
        public string Deskripsi { get; set; }
        public string NamaFile { get; set; }
        public string FilePath { get; set; }
        public string TipeMateri { get; set; }
        public Nullable<long> FileSize { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Kelas Kelas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgresMateri> ProgresMateri { get; set; }
    }
}
