//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning_Management_System.Models.Generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class NilaiQuiz
    {
        public int IdAttempt { get; set; }
        public int IdQuiz { get; set; }
        public int IdSiswa { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<System.DateTime> WaktuMulai { get; set; }
        public Nullable<System.DateTime> WaktuSubmit { get; set; }
        public string Status { get; set; }
    
        public virtual Quiz Quiz { get; set; }
        public virtual Users Users { get; set; }
    }
}
