//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning_Management_System.Models.Generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifikasi
    {
        public int IdNotif { get; set; }
        public int IdUser { get; set; }
        public string Judul { get; set; }
        public string Pesan { get; set; }
        public string TipeNotif { get; set; }
        public string UrlTujuan { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
