//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning_Management_System.Models.Generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpsiJawaban
    {
        public int IdOpsi { get; set; }
        public int IdSoal { get; set; }
        public string TeksOpsi { get; set; }
        public bool IsCorrect { get; set; }
    
        public virtual SoalQuiz SoalQuiz { get; set; }
    }
}
