//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning_Management_System.Models.Generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class PengumpulanTugas
    {
        public int IdKumpul { get; set; }
        public int IdTugas { get; set; }
        public int IdSiswa { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> WaktuKumpul { get; set; }
        public Nullable<decimal> Nilai { get; set; }
        public string Feedback { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Tugas Tugas { get; set; }
    }
}
