//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning_Management_System.Models.Generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profiles
    {
        public int IdUser { get; set; }
        public string NoHp { get; set; }
        public string Bio { get; set; }
        public string Alamat { get; set; }
        public Nullable<System.DateTime> TglLahir { get; set; }
        public string JenisKelamin { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
