//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning_Management_System.Models.Generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgresMateri
    {
        public int IdProgres { get; set; }
        public int IdMateri { get; set; }
        public int IdSiswa { get; set; }
        public bool IsSelesai { get; set; }
        public Nullable<System.DateTime> DiselesaikanPada { get; set; }
    
        public virtual Materi Materi { get; set; }
        public virtual Users Users { get; set; }
    }
}
