//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning_Management_System.Models.Generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quiz()
        {
            this.NilaiQuiz = new HashSet<NilaiQuiz>();
            this.SoalQuiz = new HashSet<SoalQuiz>();
        }
    
        public int IdQuiz { get; set; }
        public int IdKelas { get; set; }
        public int PertemuanKe { get; set; }
        public string JudulQuiz { get; set; }
        public string Deskripsi { get; set; }
        public Nullable<int> Durasi { get; set; }
        public decimal PassingScore { get; set; }
        public Nullable<System.DateTime> WaktuMulai { get; set; }
        public Nullable<System.DateTime> WaktuSelesai { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Kelas Kelas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NilaiQuiz> NilaiQuiz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoalQuiz> SoalQuiz { get; set; }
    }
}
