//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning_Management_System.Models.Generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoalQuiz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoalQuiz()
        {
            this.OpsiJawaban = new HashSet<OpsiJawaban>();
        }
    
        public int IdSoal { get; set; }
        public int IdQuiz { get; set; }
        public string Pertanyaan { get; set; }
        public string TipeSoal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpsiJawaban> OpsiJawaban { get; set; }
        public virtual Quiz Quiz { get; set; }
    }
}
