//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning_Management_System.Models.Generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class StreamPostingan
    {
        public int IdStream { get; set; }
        public int IdKelas { get; set; }
        public int IdUser { get; set; }
        public string Pesan { get; set; }
        public string AttachmentUrl { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Kelas Kelas { get; set; }
        public virtual Users Users { get; set; }
    }
}
