//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learning_Management_System.Models.Generator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tugas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tugas()
        {
            this.PengumpulanTugas = new HashSet<PengumpulanTugas>();
        }
    
        public int IdTugas { get; set; }
        public int IdKelas { get; set; }
        public int PertemuanKe { get; set; }
        public string JudulTugas { get; set; }
        public string Deskripsi { get; set; }
        public System.DateTime Deadline { get; set; }
        public string FileAttachment { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Kelas Kelas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PengumpulanTugas> PengumpulanTugas { get; set; }
    }
}
